name: Deploy to Firebase Functions

# Este workflow é acionado em duas situações:
# 1. Quando um 'push' é feito na branch 'main' (geralmente após um merge de PR).
# 2. Quando um Pull Request é aberto ou atualizado para a branch 'main'.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    # Chama o workflow reutilizável.
    uses: ./.github/workflows/reusable-build-test.yml

  # Segundo Job: Fazer o Deploy para o Firebase
  deploy:
    name: Deploy to Firebase
    # Este job só executa se o job 'build_and_test' for concluído com sucesso
    # E somente se o evento for um push para a branch 'main'.
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'functions/package.json'
          cache: 'npm'
          cache-dependency-path: 'functions/package-lock.json'

      - name: Install dependencies
        run: npm ci
        working-directory: ./functions

      - name: Build TypeScript
        run: npm run build
        working-directory: ./functions

      - name: Deploy to Firebase Functions
        uses: FirebaseExtended/action-cli@v0
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}